### PR TITLE
Remove comment number from Last 10 new commits

### PR DESCRIPTION
**Pull request by kwankyu**
Seen many times like in https://34.105.185.241/sagemath/sage-all-2023-01-14-013/issues/16266#issuecomment-4698665

### CODE REVIEW

**Comment by kwankyu** [comment]
It seems that the text is always "Last 10 new commits:", but I was not sure, and hence the regex.

**Comment by mkoeppe** [comment]
Some comments have the "Last 10 new commits" but also a real human-written comment. Does this patch also remove the comment number from those?

**Comment by kwankyu** [comment]
Perhaps yes. May I see those comments? I can try to figure out a stricter check.

**Comment by mkoeppe** [comment]
https://34.105.185.241/sagemath/sage-all-2023-01-14-013/issues/16266#issuecomment-4698668 is one example with human comment at the beginning

**Comment by kwankyu** [comment]
That is OK since it starts with a human comment. The code checks the "note" (comment) starts with "Last 10 new commits:". 

I think it is unlikely that a human comment is added after the commits block. And I think it's OK to have a few false positives.

**Comment by mkoeppe** [comment]
OK, thanks!

**Pull request merged**
