### PR TITLE
Fix E1, E13 of issue #18

### PR DESCRIPTION
**Pull request by kwankyu**
The patch would also be useful for links to images in attachments in tickets.

### CODE REVIEW

**Comment by mkoeppe** [comment]
This seems to give this change:
```
--- a/GitHub.md
+++ b/GitHub.md
@@ -1,6 +1,6 @@
 # GitHub
 
-![](https://github.githubassets.com/images/modules/logos_page/Octocat.png, height=200, right)[GitHub](https://github.com) refers to the popular source code hosting and issue tracking se
rvice.  For convenience, there is a [mirror of Sage's repository](https://github.com/sagemath/sage) on GitHub, though it should be considered read-only, and we do not accept issues or pu
ll requests to Sage through GitHub.  However, the [SageMath organization](https://github.com/sagemath) on GitHub does host a number of other ancillary repositories related to Sage, and o
ther Sage-related projects, including (but not limited to):
+[[GitHub/https://github.githubassets.com/images/modules/logos_page/Octocat.png]][GitHub](https://github.com) refers to the popular source code hosting and issue tracking service.  For c
onvenience, there is a [mirror of Sage's repository](https://github.com/sagemath/sage) on GitHub, though it should be considered read-only, and we do not accept issues or pull requests t
o Sage through GitHub.  However, the [SageMath organization](https://github.com/sagemath) on GitHub does host a number of other ancillary repositories related to Sage, and other Sage-rel
ated projects, including (but not limited to):
```
the "GitHub/" in front of https does not look right

**Comment by kwankyu** [comment]
> the "GitHub/" in front of https does not look right

Right. But the situation didn't get worse. See the link in 

https://github.com/soehms/trac_to_gh/wiki/GitHub

**Comment by soehms** [comment]
> > the "GitHub/" in front of https does not look right
> 
> Right. But the situation didn't get worse. See the link in
> 
> https://github.com/soehms/trac_to_gh/wiki/GitHub

Maybe we should convert these images with size and position options to flat html, In the exampe:

```
<img src="https://github.githubassets.com/images/modules/logos_page/Octocat.png" height=200 right>
```

This works as you can see on the [refered page](https://github.com/soehms/trac_to_gh/wiki/GitHub) (where I've changed this maually).

**Comment by kwankyu** [comment]
Done in #25.

**Pull request merged**
