### PR TITLE
Implement GitHub mention

### PR DESCRIPTION
**Pull request by kwankyu**
and fixed all issues known to me, hopefully.

It is now tricky to deal with all corner cases. I cannot be sure that a fix for one issue may not introduce more issues elsewhere. Fingers crossed. Please check.

back ticks in code snippet still do not work. I don't know how to fix this...

### CODE REVIEW

**Comment by mkoeppe** [comment]
I see a regression:
``````
diff --git a/Issues-00xxx/142.md b/Issues-00xxx/142.md
index 3f641a9856..9c00d34a05 100644
--- a/Issues-00xxx/142.md
+++ b/Issues-00xxx/142.md
@@ -3,7 +3,7 @@
 archive/issues_000142.json:
 ```json
 {
-    "body": "\n```\n>\n> Yep...  My $HOME/.sage belonged to \"root\".  I have no idea why that\n> happened either...  Maybe I used a \"sudo\" when I shouldn't...  (But I\n> really think I just used to \"make\".)  In any case, a \"sudo chown -R\"\n> fixed it.\n\nYes, this is a known bug in the install process. SAGE get's run \nduring the install, which can cause some problems like you just\nhad if the user doing the build is root but the $HOME for root\nis not /root.\n\nWilliam\n```\n\n**Assignee:** @williamstein\n\n**Resolution:** invalid\n\nIssue created by migration from https://trac.sagemath.org/ticket/142\n\n",
+    "body": "{{{>\n> Yep...  My $HOME/.sage belonged to \"root\".  I have no idea why that\n> happened either...  Maybe I used a \"sudo\" when I shouldn't...  (But I\n> really think I just used to \"make\".)  In any case, a \"sudo chown -R\"\n> fixed it.\n\n\nYes, this is a known bug in the install process. SAGE get's run \nduring the install, which can cause some problems like you just\nhad if the user doing the build is root but the $HOME for root\nis not /root.\n\nWilliam\n}}}\n\n**Assignee:** @williamstein\n\n**Resolution:** invalid\n\nIssue created by migration from https://trac.sagemath.org/ticket/142\n\n",
     "closed_at": "2007-10-21T01:48:35Z",
     "created_at": "2006-10-21T03:37:21Z",
     "labels": [
@@ -18,21 +18,20 @@ archive/issues_000142.json:
     "user": "https://github.com/williamstein"
 }
 ```
-
-```
->
+{{{>
 > Yep...  My $HOME/.sage belonged to "root".  I have no idea why that
 > happened either...  Maybe I used a "sudo" when I shouldn't...  (But I
 > really think I just used to "make".)  In any case, a "sudo chown -R"
 > fixed it.
 
+
 Yes, this is a known bug in the install process. SAGE get's run 
 during the install, which can cause some problems like you just
 had if the user doing the build is root but the $HOME for root
 is not /root.
 
 William
-```
+}}}
``````

**Comment by mkoeppe** [comment]
I also tried [d57cf21](https://github.com/sagemath/trac-to-github/pull/56/commits/d57cf2138657dcf84240dfd4667f77df90b31866) by itself, but it introduces bad mentions at the beginning of lines:
```
 * fix p-adic log -- fixed p-adic log which gave incorrect answers sometimes (trac ticket #53)
diff --git a/Issues-00xxx/545.md b/Issues-00xxx/545.md
index 06155e627c..42f06beee7 100644
--- a/Issues-00xxx/545.md
+++ b/Issues-00xxx/545.md
@@ -1717,7 +1717,7 @@ Attachment [logic4.patch](tarball://root/attachments/some-uuid/ticket545/logic4.
 
 Positive review, this should go into the 3.3 series.
 
-`@`Michael:
+@Michael:
 For this ticket, only two of the patches are to be applied (I tested against Sage3.3.alpha0 on my Mac) to the Sage Library (devel/sage-main):
 
 * "logic4.patch" (should apply cleanly, credit: Chris Gorecki)
```

**Comment by kwankyu** [comment]
> I see a regression: ... [in #142]

No. Look at #142 at trac. This is an improvement.

**Comment by mkoeppe** [comment]
Indeed. Sorry

**Comment by mkoeppe** [comment]
```
## Migrate ticket #3889 (94 changes): extend parameter for number fi
Traceback (most recent call last):
  File "/Users/mkoeppe/s/sage/trac-to-github/./migrate.py", line 1706, in <module>
    convert_issues(source, dest, only_issues = only_issues, blacklist_issues = blacklist_issues)
  File "/Users/mkoeppe/s/sage/trac-to-github/./migrate.py", line 1309, in convert_issues
    comment_data['note'] = trac2markdown(desc, '/issues/', conv_help, False)
  File "/Users/mkoeppe/s/sage/trac-to-github/./migrate.py", line 739, in trac2markdown
    text = re.sub(r'(?sm)(New commits:)\n((?:\|[^\n]*\|(?:\n|$))+)', commits_list, text)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/mkoeppe/s/sage/trac-to-github/./migrate.py", line 731, in commits_list
    commit_id = match_row.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Pull request merged**
