### PR TITLE
Fix E5 of issue #18

### PR DESCRIPTION
**Pull request by kwankyu**
See https://github.com/kwankyu/trac_to_gh/wiki/GraphTheoryRoadmap

Also fixed the resizing problem of images from attachment. See https://github.com/kwankyu/trac_to_gh/wiki

### CODE REVIEW

**Review by soehms — CHANGES_REQUESTED** [review]
These links on `symbolics.md` are broken again:


```
 ## Other Symbolic pages
- * [Symbolic functions](functions)
+ * [[Symbolic functions\|symbolics-functions]]
  * [wiki page](http://wiki.sagemath.org/symbolics) to coordinate work on new symbolics functionality.
- * [symbolics/maxima](maxima) dependencies on maxima
- * [symbolics/nonzero](nonzero) solving the zero comparison problem
+ * [[symbolics/maxima\|symbolics-maxima]] dependencies on maxima
+ * [[symbolics/nonzero\|symbolics-nonzero]] solving the zero comparison problem
  * [Pynac](http://pynac.org) bugs are tracked in [the github issue tracker](https://github.com/pynac/pynac/issues).
  * [symbolics/switch_todo](http://wiki.sagemath.org/symbolics/switch_todo) old TODO list for symbolics backend switch to pynac
```

Are we sure that the `[[..]]` syntax is working when used in issues, too? It's no official Markdown syntax and for example not rendered by `grip -b`.

Furthermore the PR introduces trailing white-spaces in some lines:

```
-See *[custom query](http://trac.sagemath.org/sage_trac/query)* to make your own queries.
+See *[custom query](http://trac.sagemath.org/sage_trac/query )* to make your own queries.
```

Even if they don't disturb anything it looks nicer without them.

**Comment by kwankyu** [comment]
Hopefully the commit to fix E4 also fixes your issues.

**Comment by kwankyu** [comment]
> Are we sure that the `[[..]]` syntax is working when used in issues, too? 

Perhaps. I am not sure.

> It's no official Markdown syntax and for example not rendered by `grip -b`.

It's here: https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content

If `[..](..)` is the official way to do it, then we may replace. Would it work for all uses? For images too?

**Comment by soehms** [comment]
> Hopefully the commit to fix E4 also fixes your issues.

Yes, it does! It looks very good, now. But you should have a look at *CamelCase* in display-text of links:

```
-See [the SageMathCell website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
\ No newline at end of file
+See [the [[SageMathCell\|SageMathCell]] website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
\ No newline at end of file
```

Structurally I would prefer that `camelcase_wiki_link` is a method of `ConversionHelper` and the literals `OPENING__DOUBLE__BRACKETS` and `CLOSING__DOUBLE__BRACKETS` are defined as constant strings (since used multiple times).

**Comment by soehms** [comment]
> > Are we sure that the `[[..]]` syntax is working when used in issues, too?
> 
> Perhaps. I am not sure.
> 
> > It's no official Markdown syntax and for example not rendered by `grip -b`.
> 
> It's here: https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content
> 
> If `[..](..)` is the official way to do it, then we may replace. Would it work for all uses? For images too?

If it works for issues then it's fine. But we should check this to have it working for ticket migration, too.

**Comment by soehms** [comment]
> > > Are we sure that the `[[..]]` syntax is working when used in issues, too?
> > 
> > 
> > Perhaps. I am not sure.
> > > It's no official Markdown syntax and for example not rendered by `grip -b`.
> > 
> > 
> > It's here: https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content
> > If `[..](..)` is the official way to do it, then we may replace. Would it work for all uses? For images too?
> 
> If it works for issues then it's fine. But we should check this to have it working for ticket migration, too.

I just tried to create an according issue in the [trac_to_gh](https://github.com/sagemath/trac_to_gh/issues) repository. But even the preview did not render it:

image

**Comment by kwankyu** [comment]
> ... But you should have a look at _CamelCase_ in display-text of links:
> 
> ```
> -See [the SageMathCell website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
> \ No newline at end of file
> +See [the [[SageMathCell\|SageMathCell]] website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
> \ No newline at end of file
> ```

Right. It seems hard to exclude these cases by just regex.

> Structurally I would prefer that `camelcase_wiki_link` is a method of `ConversionHelper` and the literals `OPENING__DOUBLE__BRACKETS` and `CLOSING__DOUBLE__BRACKETS` are defined as constant strings (since used multiple times).

I don't disagree. It's welcome if you work on that.

**Comment by kwankyu** [comment]
> I just tried to create an according issue in the [trac_to_gh](https://github.com/sagemath/trac_to_gh/issues) repository. But even the preview did not render it

Then we should fix it. Would you work on it?

**Comment by soehms** [comment]
> > I just tried to create an according issue in the [trac_to_gh](https://github.com/sagemath/trac_to_gh/issues) repository. But even the preview did not render it
> 
> Then we should fix it. Would you work on it?

I can have a look at that, too!

**Comment by soehms** [comment]
> > > I just tried to create an according issue in the [trac_to_gh](https://github.com/sagemath/trac_to_gh/issues) repository. But even the preview did not render it
> > 
> > 
> > Then we should fix it. Would you work on it?
> 
> I can have a look at that, too!

I experimented a bit (see [issue 30](https://github.com/sagemath/trac_to_gh/issues/30) in the [trac_to_gh](https://github.com/sagemath/trac-to-github) repository), but I haven't found any way to use relative links successfully.

So I think we'll leave it as it is. When we do the ticket migration, we can set a flag in the configuration file to replace these links with global references.

**Comment by soehms** [comment]
> > > > I just tried to create an according issue in the [trac_to_gh](https://github.com/sagemath/trac_to_gh/issues) repository. But even the preview did not render it
> > > 
> > > 
> > > Then we should fix it. Would you work on it?
> > 
> > 
> > I can have a look at that, too!
> 
> I experimented a bit (see [issue 30](https://github.com/sagemath/trac_to_gh/issues/30) in the [trac_to_gh](https://github.com/sagemath/trac-to-github) repository), but I haven't found any way to use relative links successfully.

In the meantime I've seen that I gave up a bit to early (since my train was arriving). From an issue a wiki page (for example `SageMath`) can be references by Markdown syntax `[SageMath](../wiki/SageMath)` (see the according update in issue 30). But pages having white-spaces in their names need some extra attention. What has been the reason for not putting `symbolics functions.md` into the sub-directory `symbolics` as `function.md`-file? Why do we need white-spaces in the filenames?

 
Anyway, this reference syntax does not work inside the wiki.

**Comment by kwankyu** [comment]
> ... But pages having white-spaces in their names need some extra attention. What has been the reason for not putting `symbolics functions.md` into the sub-directory `symbolics` as `function.md`-file? Why do we need white-spaces in the filenames?

Because Github wiki does not respect folders. The `function.md` is referred by `function` instead of `symbolics/function`. This makes wiki page names ambiguous.

Anyway, I could remove `[[ .. ]]` syntax. See PR #28.

**Comment by kwankyu** [comment]
> > ... But you should have a look at _CamelCase_ in display-text of links:
> > ```
> > -See [the SageMathCell website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
> > \ No newline at end of file
> > +See [the [[SageMathCell\|SageMathCell]] website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
> > \ No newline at end of file
> > ```
> 
> Right. It seems hard to exclude these cases by just regex.

Implemented smarter CamelCase wiki link converter in PR #28.

**Comment by soehms** [comment]
> > > ... But you should have a look at _CamelCase_ in display-text of links:
> > > ```
> > > -See [the SageMathCell website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
> > > \ No newline at end of file
> > > +See [the [[SageMathCell\|SageMathCell]] website](https://sagecell.sagemath.org/static/about.html?v=66c8a2df011da3aea3dfa789fc6117f4) for more details, including how to embed it in your own web pages.
> > > \ No newline at end of file
> > > ```
> > 
> > 
> > Right. It seems hard to exclude these cases by just regex.
> 
> Implemented smarter CamelCase wiki link converter in PR #28.

This I've already done in PR #27 together with a fix of CamelCase at EOL. Furthermore, I improved the Code structure. Sorry that I forgot to mention that here. I would apreciate if you would merge that.

**Comment by kwankyu** [comment]
> This I've already done in PR #27 together with a fix of CamelCase at EOL. Furthermore, I improved the Code structure. 

Sorry. I missed that. I cherry-picked your commit to PR #28. Thanks.

**Pull request merged**
