### PR TITLE
Fix replying to

### LINKED ISSUE #93: Convert username in "Replying to [comment:... user]" to GitHub username

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #93.

### CODE REVIEW

**Comment by mkoeppe** [comment]
I think this should use the `gh_username` function, which also knows how to convert `gh-...` usernames

**Comment by kwankyu** [comment]
`gh_username` gets `dest` argument, which is not used. That argument is not available in `trac2markdown`. 

`gh_username` returns not exactly the github user name, but one prefixed with `@`. 

So how about defining `convert_trac_username` that does not get `dest` and returns the proper username (without `@` prefix), and making `gh_username` use `convert_trac_username`?

**Comment by kwankyu** [comment]
Or `gh_convert_trac_username`...

**Comment by mkoeppe** [comment]
> `gh_username` returns not exactly the github user name, but one prefixed with `@`

That's right, but with the @ is how we would typically want to show the GitHub user name

**Comment by kwankyu** [comment]
So `Replying to @williamstein` is right? Okay then I will prefix the proper github username (what is returned from `gh_convert_trac_username`) with `@`.

**Comment by mkoeppe** [comment]
Yes, I think so; that should create a mention

**Comment by kwankyu** [comment]
I will user `convert_trac_username` as it does not get `dest` argument unlike other functions `gh_...`

**Comment by kwankyu** [comment]
> Yes, I think so; that should create a mention

Then on the migration date, they will get lots of notification emails?

**Comment by mkoeppe** [comment]
I'd hope it doesn't create notifications on import, but I can't be sure

**Comment by mkoeppe** [comment]
Working great, thank you!

**Pull request merged**
