### PR TITLE
Fine-tune comment numbers

### LINKED ISSUE #121: Fine-tuning comment number
Recent addition of comment numbers does not work quite well.

I realized that we can get rid of the previous ugly blank space leading comments just by
```
<div id="comment:1"></div>
```
instead of using an anchor tag. 

If we still want to show the comment number (I think we do), we can do
```
<div id="comment:1" align="right">Comment 1</div>
```
Non-bold text seems better as it does not draw attention.

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #121.

### CODE REVIEW

**Comment by kwankyu** [comment]
By the way, I don't understand why "Branch pushed .." (see https://34.105.185.241/sagemath/sage-all-2023-01-12-003/issues/34794#issuecomment-1326977) has comment number unlike other auto-generated comments.

**Comment by mkoeppe** [comment]
Because that is an actual comment, not an attribute change, in Trac.

**Comment by mkoeppe** [comment]
Looks like this is messing up markdown formatting in the following paragraph
https://34.105.185.241/sagemath/sage-20230113195040/issues/30233#comment:7

**Comment by kwankyu** [comment]
I am out of town for a few days.

**Pull request merged**
