### PR TITLE
Update migrate.cfg.sagetracmigrationarchive

### PR DESCRIPTION
**Pull request by fchapoton**
add some missing aliases

### CODE REVIEW

**Comment by mkoeppe** [comment]
If these are legitimate duplicate Trac user accounts (not just typos), it's best to add them to https://github.com/sagemath/website/blob/master/conf/contributors.xml instead, from which this list is generated (the `trac` attribute there can be a comma-separated list).

**Comment by fchapoton** [comment]
fhivert is a typo, wstein I am not sure

**Comment by fchapoton** [comment]
@williamstein  did you ever use the "wstein" login for trac or always only "was" ?

**Comment by fchapoton** [comment]
There is no wstein user on trac

**Comment by mkoeppe** [comment]
I'll merge this after taking care of #106. Thanks!

**Pull request merged**
