### PR TITLE
Fix commits list problem

### PR DESCRIPTION
**Pull request by kwankyu**
Seen in https://34.105.185.241/sagemath/sage-prod-2023-01-30-077/issues/34956#issuecomment-7308003

Checking regression...

### CODE REVIEW

**Comment by kwankyu** [comment]
Affected cases might be very rare.

It takes me long to check regression. Would you check?

**Comment by kwankyu** [comment]
> Affected cases should be very rare.

Our converter is now smarter than Trac, as seen in 
```
-I made a change like this, but changing `2008`} to `{2008`}}.  The second brace } matches the one a few lines earlier, in the line `@manual{sage`.  (The change wasn't really necessary, but it doesn't hurt, either.)
+I made a change like this, but changing `2008}` to `{2008}}`.  The second brace } matches the one a few lines earlier, in the line `@manual{sage`.  (The change wasn't really necessary, but it doesn't hurt, either.) 
```
for [trac #1389](https://trac.sagemath.org/ticket/1389#comment:17)

**Comment by mkoeppe** [comment]
Yes, I just ran it and there's a long long diff. 
[pr171.diff.gz](https://github.com/sagemath/trac-to-github/files/10553148/pr171.diff.gz)

I'll try to find time this evening to review it

**Comment by kwankyu** [comment]
I checked through the diff file. There are two cases:

- positive change (most of them), like 
```diff
-whereas the parent should be `Ordered set partitions of {1,2,3,4,5,6`}
+whereas the parent should be `Ordered set partitions of {1,2,3,4,5,6}`  
```

- slightly negative change (a few, where the writer made a mistake of typing 4 braces `}}}}` instead of 3 `}}}`):
```diff
-maybe you should add `r"""`} when the doctests contains something that can perturb the pdf doc ?
+maybe you should add `r"""}` when the doctests contains something that can perturb the pdf doc ?    
```

I definitely recommend to take this PR.

**Comment by mkoeppe** [comment]
I agree, looking good. Thank you!

**Comment by kwankyu** [comment]
Thanks!

**Pull request merged**
