### PR TITLE
Fix errors in comment links and attachment links

### LINKED ISSUE #133: "This is the Trac macro comment:30 that was inherited from the migration" appears in issue comment
https://34.105.185.241/sagemath/sage-20230114144245/issues/33453#comment:33

@kwankyu

### PR DESCRIPTION
**Pull request by kwankyu**
Fix #133.

Check for regression is under way.

### CODE REVIEW

**Comment by kwankyu** [comment]
My check was screwed up somehow. Please check regression on your side.

**Comment by kwankyu** [comment]
Not that a regression is likely.

**Comment by kwankyu** [comment]
I recognized lots of errors in attachment links. This PR seems to fix them all.

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
