### PR TITLE
Fix E3 of issue #18

### PR DESCRIPTION
**Pull request by kwankyu**

### CODE REVIEW

**Comment by kwankyu** [comment]
As suggested by Sebastian.

**Review by soehms — APPROVED** [review]
LGTM

**Comment by soehms** [comment]
One question in connection with the former PR #24: It looks as if we still ignore size arguments for attachments:

```
-![](ticket_badges.png, 547px)
+[[Home/ticket_badges.png]]
```

Is this intended? Or because there is no better solution? My observation is that `` works in the preview (see the accordingly manually changed [Home.md](https://github.com/soehms/trac_to_gh/wiki/Home)) but unfortunately not after saving the page.

**Comment by kwankyu** [comment]
> Is this intended? Or because there is no better solution? 

Yes. But I found a better solution. See #26.

**Pull request merged**
