### PR TITLE
Add comment number to issue comments

### PR DESCRIPTION
**Pull request by kwankyu**
Apart from the last line in the changes for the issue #107, other changes are just refactoring to clean up things.

### CODE REVIEW

**Comment by kwankyu** [comment]
> Though the comment links are rewritten to use the fragment URL, at least on some tickets, ticket comments refer to earlier ticket comments by number without using the correct format.

I don't understand this.

> But perhaps if it is followed by the "Replying to [...]" message, the "\n" can be suppressed?

I don't know.

Perhaps we need to see how the comment numbers are shown in GES.

**Comment by mkoeppe** [comment]
I think there's no need to keep the format "comment:123" because we replace all occurrences of this format when it appears in links. How about "Comment 123:"?

**Comment by kwankyu** [comment]
The converted issues in GES look somewhat different than in migration archive. Let's see how it looks.

**Comment by kwankyu** [comment]
Will we see all tickets in GES soon?

**Comment by mkoeppe** [comment]
> Will we see all tickets in GES soon?

Yes, the conversion is running. It's taking quite a few hours for the full run. It's at 70% now...

**Comment by kwankyu** [comment]
Could we see converted issues with comment numbers in GES by a run separate from the current full run?

**Pull request merged**
