### PR TITLE
Fix errors in codeblock and comment link

### PR DESCRIPTION
**Pull request by kwankyu**
This fixes some errors seen in #34850.

Most importantly, this fixes a regression introduced in #140.

### CODE REVIEW

**Comment by kwankyu** [comment]
Apart from this PR, the converted issue #34850 has other strange problem. See 

https://34.105.185.241/sagemath/sage-all-2023-01-14-013/issues/34850#issuecomment-5051930

where comments are wrongly ordered. See also 

https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-34xxx/34850.md#comment:88

where comments after comment:88 are truncated.

Compare them with

https://trac.sagemath.org/ticket/34850

**Comment by kwankyu** [comment]
The problem in 

https://github.com/kwankyu/trac-to-github/blob/check/wiki/Issues-34xxx/34850.md#comment:88

might be an outdated cache problem. I don't know for sure...

**Comment by mkoeppe** [comment]
> https://34.105.185.241/sagemath/sage-all-2023-01-14-013/issues/34850#issuecomment-5051930
> 
> where comments are wrongly ordered. 

Somehow comment:100 is labeled as comment:0 etc.

**Comment by mkoeppe** [comment]
Fixed in ddbce7f

**Comment by mkoeppe** [comment]
This branch looks like a good fix, but I also see what looks like a regression regarding comment links:
``````
diff --git a/Issues-12xxx/12655.md b/Issues-12xxx/12655.md
index ff11bd8fb3a..83dff28fc95 100644
--- a/Issues-12xxx/12655.md
+++ b/Issues-12xxx/12655.md
@@ -2108,7 +2108,7 @@ diff -r f4822b70da5b SPKG.txt
 +   - nf.h.patch -- Fixing preprocessor misconception                           
 + * Sage Trac #12750:                                                           
 +   - base_lookup.patch -- Fixing explict name lookup in template base (gcc 4.7)
-+ * Sage Trac #12655, [comment:29](#comment:29):
++ * Sage Trac #12655, comment:29:
 +   - SConstruct.patch -- Fixing gcc components on sun
 +
 +All patches were merged upstream.
`````

**Comment by mkoeppe** [comment]
It's not a regression

**Comment by kwankyu** [comment]
Right. Thanks.

**Pull request merged**
