### PR TITLE
Some cosmetic changes

### PR DESCRIPTION
**Pull request by kwankyu**
implemented issue #48 

also fixed https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1365537676

See https://github.com/kwankyu/trac_to_gh/wiki/27996

and fixed problems in https://github.com/sagemath/trac-to-github/issues/18#issuecomment-1365555570

See https://github.com/kwankyu/trac_to_gh/wiki/34393

### CODE REVIEW

**Comment by kwankyu** [comment]
I am not sure if bold texts are too many or too few. Feel free to change them further.

**Comment by mkoeppe** [comment]
Thank you!

**Comment by mkoeppe** [comment]
I've made a small change to it in 16ffce4

**Comment by mkoeppe** [comment]
On `ticket #14648` I am getting
```
  File "/Users/mkoeppe/s/sage/trac-to-github/./migrate.py", line 657, in commits_list
    _, commit_id, commit_message, _ = c.split('|')
ValueError: too many values to unpack (expected 4)
```

**Comment by mkoeppe** [comment]
Working around it in 4c22fe4

**Comment by kwankyu** [comment]
> Working around it in [4c22fe4](https://github.com/sagemath/trac-to-github/commit/4c22fe4fc2cbf4e14516d4b44acc28ee88294e31)

I have a fix. Would you revert this?

**Comment by mkoeppe** [comment]
You can revert by workaround in your PR

**Comment by mkoeppe** [comment]
Also https://github.com/sagemath/trac_to_gh/blob/main/Issues-27xxx/27533.md#comment:1  is affected by a parsing error

**Pull request merged**
