### PR TITLE
Add more prefixes to some labels

### PR DESCRIPTION
**Pull request by tobiasdiez**
I was not able to test it...

### CODE REVIEW

**Comment by kwankyu** [comment]
Here "pending" has prefix "s: ", while in the previous discussion, "pending" has no prefix according to https://github.com/sagemath/trac-to-github/issues/99#issuecomment-1413542971.

**Comment by kwankyu** [comment]
I am okay with either way for now.

**Comment by mkoeppe** [comment]
I'll have to run another round of imports tomorrow, so this can still be fixed. PR?

**Comment by kwankyu** [comment]
I am preparing a PR. "pending" is missing in `label_colors`. Is it okay or should I add?

**Comment by kwankyu** [comment]
"t: feature" is not either in `label_colors`.

**Comment by kwankyu** [comment]
On the other hand, we have "resolution" in `label_colors`. But we don't have "resolution" label. Right?

**Comment by mkoeppe** [comment]
`resolution` is a "label_category"; this color affects all labels that are created when mapping Trac resolutions - https://github.com/sagemath/trac-to-github/blob/master/migrate.py#L2362

**Comment by mkoeppe** [comment]
After these PRs, unfortunately labels / colors are messed up

**Pull request merged**
