### PR TITLE
Sort description items by order

### PR DESCRIPTION
**Pull request by kwankyu**
Sort description items in this

`order = ['cc:', 'component', 'keywords', 'author', 'reviewer', 'branch', 'commit', 'depends']`

Other items, if any, follow in alphabetical order.

### CODE REVIEW

**Comment by kwankyu** [comment]
Of course, you can control the order. I am not sure if "cc:" should be between "keywords" and "author".

**Comment by mkoeppe** [comment]
I think "Depends" should be the very first item because it has a different format that makes it seems more like part of the text. 

The rest of the order looks good to me. In particular, having "Author" precede "Reviewer" is, of course, a great improvement.

**Comment by mkoeppe** [comment]
Also Author - Branch/Commit - Reviewer would make sense to me; but I don't have a clear preference on that

**Comment by mkoeppe** [comment]
With some more fields:
```
order = ['depends', 'upstream', 'cc:', 'component', 'keywords', 'author', 'branch', 'commit', 'reviewer', 'merged']
```

**Comment by kwankyu** [comment]
Done.

**Comment by kwankyu** [comment]
While I am at it, why names in CC are not separated by commas?

**Comment by kwankyu** [comment]
I saw `branch @ commit` format. Is this an official format?

**Comment by mkoeppe** [comment]
> why names in CC are not separated by commas?

Because one wouldn't use commas in a list of at-mentions.

**Comment by kwankyu** [comment]
OK if that's a convention.

**Comment by mkoeppe** [comment]
> I saw `branch @ commit` format. Is this an official format?

It's not syntax. It is intended to expresses that we are sitting on the branch "at" this commit.

**Comment by kwankyu** [comment]
> I think "Depends" should be the very first item because it has a different format that makes it seems more like part of the text.

At the same time, it is separated from the text by 2 spaces, and has least significant information, which is perhaps why it is placed at the last line in trac. We may regard it as a third block among 4 blocks (the last one is "Issue created by ...")

**Comment by mkoeppe** [comment]
I don't know if it matters, but to me the order `['depends', 'upstream', 'cc:', 'component', 'keywords', 'assignee', 'author', 'branch', 'commit', 'reviewer', 'merged']` makes sense "chronologically".

**Comment by kwankyu** [comment]
> > I saw `branch @ commit` format. Is this an official format?
> 
> It's not syntax. It is intended to expresses that we are sitting on the branch "at" this commit.

If it's not an official form in git culture, I doubt if people will get the intention easily...  Anyway OK with me.

**Comment by kwankyu** [comment]
> I don't know if it matters, but to me the order `['depends', 'upstream', 'cc:', 'component', 'keywords', 'assignee', 'author', 'branch', 'commit', 'reviewer', 'merged']` makes sense "chronologically".

I have no more argument. I respect your judgment :-)

**Comment by mkoeppe** [comment]
Thank you!

**Pull request merged**
