### PR TITLE
Fix backticks issue

### PR DESCRIPTION
**Pull request by kwankyu**
and other failures including

https://github.com/sagemath/trac-to-github/pull/56#issuecomment-1366140000

https://github.com/sagemath/trac-to-github/pull/56#issuecomment-1366325874

### CODE REVIEW

**Comment by kwankyu** [comment]
Hmm. I spotted still an error. Wait a minute.

**Comment by kwankyu** [comment]
It seems okay now.

**Comment by kwankyu** [comment]
and I turned off some conversions related with SVN changesets. Perhaps we need not these.

**Comment by mkoeppe** [comment]
rebased, removed `trac_cache` checked in by mistake

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
